#ifndef GUARD_CONSTANTS_MUGSHOTS_H
#define GUARD_CONSTANTS_MUGSHOTS_H

#define MUGSHOT_CUTSCENE_NEW_GAME 0
#define MUGSHOT_CUTSCENE_INTRO1BR 1
#define MUGSHOT_CUTSCENE_INTRO2BR 2
#define MUGSHOT_CUTSCENE_INTRO1EN 3
#define MUGSHOT_CUTSCENE_INTRO2EN 4

#endif